import { Note, User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alice Johnson',
    email: 'alice@student.college.edu',
    role: 'student',
    department: 'Computer Science',
    semester: '4',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-2',
    name: 'Dr. Robert Smith',
    email: 'robert@faculty.college.edu',
    role: 'faculty',
    department: 'Computer Science',
    semester: '',
    createdAt: new Date().toISOString(),
  }
];

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    title: 'Data Structures and Algorithms - Trees',
    description: 'Comprehensive notes on binary trees, AVL trees, and B-trees.',
    subject: 'Data Structures',
    department: 'Computer Science',
    semester: '3',
    unit: 'Unit 4',
    topic: 'Trees',
    fileUrl: '#',
    fileType: 'PDF',
    uploadedBy: 'user-2',
    uploaderName: 'Dr. Robert Smith',
    status: 'approved',
    downloads: 145,
    rating: 4.8,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'note-2',
    title: 'Operating Systems - Process Scheduling',
    description: 'Detailed explanation of CPU scheduling algorithms with examples.',
    subject: 'Operating Systems',
    department: 'Computer Science',
    semester: '4',
    unit: 'Unit 2',
    topic: 'Process Scheduling',
    fileUrl: '#',
    fileType: 'PDF',
    uploadedBy: 'user-1',
    uploaderName: 'Alice Johnson',
    status: 'approved',
    downloads: 89,
    rating: 4.5,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'note-3',
    title: 'Database Management Systems - Normalization',
    description: 'Notes on 1NF, 2NF, 3NF and BCNF.',
    subject: 'Database Management System',
    department: 'Information Technology',
    semester: '4',
    unit: 'Unit 3',
    topic: 'Normalization',
    fileUrl: '#',
    fileType: 'DOCX',
    uploadedBy: 'user-1',
    uploaderName: 'Alice Johnson',
    status: 'pending',
    downloads: 0,
    rating: 0,
    createdAt: new Date().toISOString(),
  }
];
